/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedStoneRouteImport } from './routes/_authenticated/stone'
import { Route as AuthenticatedRazaoRouteImport } from './routes/_authenticated/razao'
import { Route as AuthenticatedLancarRouteImport } from './routes/_authenticated/lancar'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedARevisarRouteImport } from './routes/_authenticated/a-revisar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoneRoute = AuthenticatedStoneRouteImport.update({
  id: '/stone',
  path: '/stone',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRazaoRoute = AuthenticatedRazaoRouteImport.update({
  id: '/razao',
  path: '/razao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLancarRoute = AuthenticatedLancarRouteImport.update({
  id: '/lancar',
  path: '/lancar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedARevisarRoute = AuthenticatedARevisarRouteImport.update({
  id: '/a-revisar',
  path: '/a-revisar',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/a-revisar': typeof AuthenticatedARevisarRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/lancar': typeof AuthenticatedLancarRoute
  '/razao': typeof AuthenticatedRazaoRoute
  '/stone': typeof AuthenticatedStoneRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/a-revisar': typeof AuthenticatedARevisarRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/lancar': typeof AuthenticatedLancarRoute
  '/razao': typeof AuthenticatedRazaoRoute
  '/stone': typeof AuthenticatedStoneRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/a-revisar': typeof AuthenticatedARevisarRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/lancar': typeof AuthenticatedLancarRoute
  '/_authenticated/razao': typeof AuthenticatedRazaoRoute
  '/_authenticated/stone': typeof AuthenticatedStoneRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/a-revisar'
    | '/hoje'
    | '/importacoes'
    | '/lancar'
    | '/razao'
    | '/stone'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/a-revisar'
    | '/hoje'
    | '/importacoes'
    | '/lancar'
    | '/razao'
    | '/stone'
    | '/usuarios'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/a-revisar'
    | '/_authenticated/hoje'
    | '/_authenticated/importacoes'
    | '/_authenticated/lancar'
    | '/_authenticated/razao'
    | '/_authenticated/stone'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stone': {
      id: '/_authenticated/stone'
      path: '/stone'
      fullPath: '/stone'
      preLoaderRoute: typeof AuthenticatedStoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/razao': {
      id: '/_authenticated/razao'
      path: '/razao'
      fullPath: '/razao'
      preLoaderRoute: typeof AuthenticatedRazaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lancar': {
      id: '/_authenticated/lancar'
      path: '/lancar'
      fullPath: '/lancar'
      preLoaderRoute: typeof AuthenticatedLancarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/a-revisar': {
      id: '/_authenticated/a-revisar'
      path: '/a-revisar'
      fullPath: '/a-revisar'
      preLoaderRoute: typeof AuthenticatedARevisarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedARevisarRoute: typeof AuthenticatedARevisarRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedLancarRoute: typeof AuthenticatedLancarRoute
  AuthenticatedRazaoRoute: typeof AuthenticatedRazaoRoute
  AuthenticatedStoneRoute: typeof AuthenticatedStoneRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedARevisarRoute: AuthenticatedARevisarRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedLancarRoute: AuthenticatedLancarRoute,
  AuthenticatedRazaoRoute: AuthenticatedRazaoRoute,
  AuthenticatedStoneRoute: AuthenticatedStoneRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
